//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personal.Health.Record.HospitalReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Patient", Namespace="http://schemas.datacontract.org/2004/07/Hospital.Models")]
    [System.SerializableAttribute()]
    public partial class Patient : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BirhtDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecondNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BirhtDate {
            get {
                return this.BirhtDateField;
            }
            set {
                if ((object.ReferenceEquals(this.BirhtDateField, value) != true)) {
                    this.BirhtDateField = value;
                    this.RaisePropertyChanged("BirhtDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecondName {
            get {
                return this.SecondNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SecondNameField, value) != true)) {
                    this.SecondNameField = value;
                    this.RaisePropertyChanged("SecondName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HospitalModel", Namespace="http://schemas.datacontract.org/2004/07/Hospital.Models")]
    [System.SerializableAttribute()]
    public partial class HospitalModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long HospitalIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long HospitalId {
            get {
                return this.HospitalIdField;
            }
            set {
                if ((this.HospitalIdField.Equals(value) != true)) {
                    this.HospitalIdField = value;
                    this.RaisePropertyChanged("HospitalId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Doctor", Namespace="http://schemas.datacontract.org/2004/07/Hospital.Models")]
    [System.SerializableAttribute()]
    public partial class Doctor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long DoctorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecondNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpecializationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long DoctorId {
            get {
                return this.DoctorIdField;
            }
            set {
                if ((this.DoctorIdField.Equals(value) != true)) {
                    this.DoctorIdField = value;
                    this.RaisePropertyChanged("DoctorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecondName {
            get {
                return this.SecondNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SecondNameField, value) != true)) {
                    this.SecondNameField = value;
                    this.RaisePropertyChanged("SecondName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Specialization {
            get {
                return this.SpecializationField;
            }
            set {
                if ((object.ReferenceEquals(this.SpecializationField, value) != true)) {
                    this.SpecializationField = value;
                    this.RaisePropertyChanged("Specialization");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Allergy", Namespace="http://schemas.datacontract.org/2004/07/Hospital.Models")]
    [System.SerializableAttribute()]
    public partial class Allergy : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long AllergyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AllergyNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long AllergyId {
            get {
                return this.AllergyIdField;
            }
            set {
                if ((this.AllergyIdField.Equals(value) != true)) {
                    this.AllergyIdField = value;
                    this.RaisePropertyChanged("AllergyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AllergyName {
            get {
                return this.AllergyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AllergyNameField, value) != true)) {
                    this.AllergyNameField = value;
                    this.RaisePropertyChanged("AllergyName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="History", Namespace="http://schemas.datacontract.org/2004/07/Hospital.Models")]
    [System.SerializableAttribute()]
    public partial class History : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiagnoseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long DoctorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long HistoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long HospitalIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long PatientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date {
            get {
                return this.DateField;
            }
            set {
                if ((object.ReferenceEquals(this.DateField, value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Diagnose {
            get {
                return this.DiagnoseField;
            }
            set {
                if ((object.ReferenceEquals(this.DiagnoseField, value) != true)) {
                    this.DiagnoseField = value;
                    this.RaisePropertyChanged("Diagnose");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long DoctorId {
            get {
                return this.DoctorIdField;
            }
            set {
                if ((this.DoctorIdField.Equals(value) != true)) {
                    this.DoctorIdField = value;
                    this.RaisePropertyChanged("DoctorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long HistoryId {
            get {
                return this.HistoryIdField;
            }
            set {
                if ((this.HistoryIdField.Equals(value) != true)) {
                    this.HistoryIdField = value;
                    this.RaisePropertyChanged("HistoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long HospitalId {
            get {
                return this.HospitalIdField;
            }
            set {
                if ((this.HospitalIdField.Equals(value) != true)) {
                    this.HospitalIdField = value;
                    this.RaisePropertyChanged("HospitalId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long PatientId {
            get {
                return this.PatientIdField;
            }
            set {
                if ((this.PatientIdField.Equals(value) != true)) {
                    this.PatientIdField = value;
                    this.RaisePropertyChanged("PatientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonField, value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ScheduledVisitation", Namespace="http://schemas.datacontract.org/2004/07/Hospital.Models")]
    [System.SerializableAttribute()]
    public partial class ScheduledVisitation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long DoctorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long HospitalIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long PatientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long VisitationIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date {
            get {
                return this.DateField;
            }
            set {
                if ((object.ReferenceEquals(this.DateField, value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long DoctorId {
            get {
                return this.DoctorIdField;
            }
            set {
                if ((this.DoctorIdField.Equals(value) != true)) {
                    this.DoctorIdField = value;
                    this.RaisePropertyChanged("DoctorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long HospitalId {
            get {
                return this.HospitalIdField;
            }
            set {
                if ((this.HospitalIdField.Equals(value) != true)) {
                    this.HospitalIdField = value;
                    this.RaisePropertyChanged("HospitalId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long PatientId {
            get {
                return this.PatientIdField;
            }
            set {
                if ((this.PatientIdField.Equals(value) != true)) {
                    this.PatientIdField = value;
                    this.RaisePropertyChanged("PatientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonField, value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long VisitationId {
            get {
                return this.VisitationIdField;
            }
            set {
                if ((this.VisitationIdField.Equals(value) != true)) {
                    this.VisitationIdField = value;
                    this.RaisePropertyChanged("VisitationId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HospitalReference.IHospitalService")]
    public interface IHospitalService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/getPatient", ReplyAction="http://tempuri.org/IHospitalService/getPatientResponse")]
        Personal.Health.Record.HospitalReference.Patient[] getPatient(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/getPatient", ReplyAction="http://tempuri.org/IHospitalService/getPatientResponse")]
        System.Threading.Tasks.Task<Personal.Health.Record.HospitalReference.Patient[]> getPatientAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/getUserByUsernameAndPassword", ReplyAction="http://tempuri.org/IHospitalService/getUserByUsernameAndPasswordResponse")]
        Personal.Health.Record.HospitalReference.Patient[] getUserByUsernameAndPassword(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/getUserByUsernameAndPassword", ReplyAction="http://tempuri.org/IHospitalService/getUserByUsernameAndPasswordResponse")]
        System.Threading.Tasks.Task<Personal.Health.Record.HospitalReference.Patient[]> getUserByUsernameAndPasswordAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/getUserByEGNAndPassword", ReplyAction="http://tempuri.org/IHospitalService/getUserByEGNAndPasswordResponse")]
        Personal.Health.Record.HospitalReference.Patient[] getUserByEGNAndPassword(string egn, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/getUserByEGNAndPassword", ReplyAction="http://tempuri.org/IHospitalService/getUserByEGNAndPasswordResponse")]
        System.Threading.Tasks.Task<Personal.Health.Record.HospitalReference.Patient[]> getUserByEGNAndPasswordAsync(string egn, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/AddNewPatient", ReplyAction="http://tempuri.org/IHospitalService/AddNewPatientResponse")]
        string AddNewPatient(string id, string gender, string username, string password, string first_name, string second_name, string last_name, string egn, string age, string birth_date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/AddNewPatient", ReplyAction="http://tempuri.org/IHospitalService/AddNewPatientResponse")]
        System.Threading.Tasks.Task<string> AddNewPatientAsync(string id, string gender, string username, string password, string first_name, string second_name, string last_name, string egn, string age, string birth_date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/getHospital", ReplyAction="http://tempuri.org/IHospitalService/getHospitalResponse")]
        Personal.Health.Record.HospitalReference.HospitalModel[] getHospital(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/getHospital", ReplyAction="http://tempuri.org/IHospitalService/getHospitalResponse")]
        System.Threading.Tasks.Task<Personal.Health.Record.HospitalReference.HospitalModel[]> getHospitalAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/getDoctor", ReplyAction="http://tempuri.org/IHospitalService/getDoctorResponse")]
        Personal.Health.Record.HospitalReference.Doctor[] getDoctor(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/getDoctor", ReplyAction="http://tempuri.org/IHospitalService/getDoctorResponse")]
        System.Threading.Tasks.Task<Personal.Health.Record.HospitalReference.Doctor[]> getDoctorAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/getDoctorByHospitalId", ReplyAction="http://tempuri.org/IHospitalService/getDoctorByHospitalIdResponse")]
        Personal.Health.Record.HospitalReference.Doctor[] getDoctorByHospitalId(string hospital_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/getDoctorByHospitalId", ReplyAction="http://tempuri.org/IHospitalService/getDoctorByHospitalIdResponse")]
        System.Threading.Tasks.Task<Personal.Health.Record.HospitalReference.Doctor[]> getDoctorByHospitalIdAsync(string hospital_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/getAllAllergies", ReplyAction="http://tempuri.org/IHospitalService/getAllAllergiesResponse")]
        Personal.Health.Record.HospitalReference.Allergy[] getAllAllergies();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/getAllAllergies", ReplyAction="http://tempuri.org/IHospitalService/getAllAllergiesResponse")]
        System.Threading.Tasks.Task<Personal.Health.Record.HospitalReference.Allergy[]> getAllAllergiesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/AddNewAllergy", ReplyAction="http://tempuri.org/IHospitalService/AddNewAllergyResponse")]
        string AddNewAllergy(string allergy_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/AddNewAllergy", ReplyAction="http://tempuri.org/IHospitalService/AddNewAllergyResponse")]
        System.Threading.Tasks.Task<string> AddNewAllergyAsync(string allergy_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/getHospitalRecord", ReplyAction="http://tempuri.org/IHospitalService/getHospitalRecordResponse")]
        Personal.Health.Record.HospitalReference.History[] getHospitalRecord(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/getHospitalRecord", ReplyAction="http://tempuri.org/IHospitalService/getHospitalRecordResponse")]
        System.Threading.Tasks.Task<Personal.Health.Record.HospitalReference.History[]> getHospitalRecordAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/getHospitalRecordByPatientID", ReplyAction="http://tempuri.org/IHospitalService/getHospitalRecordByPatientIDResponse")]
        Personal.Health.Record.HospitalReference.History[] getHospitalRecordByPatientID(string patient_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/getHospitalRecordByPatientID", ReplyAction="http://tempuri.org/IHospitalService/getHospitalRecordByPatientIDResponse")]
        System.Threading.Tasks.Task<Personal.Health.Record.HospitalReference.History[]> getHospitalRecordByPatientIDAsync(string patient_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/getHospitalRecordByHospitalID", ReplyAction="http://tempuri.org/IHospitalService/getHospitalRecordByHospitalIDResponse")]
        Personal.Health.Record.HospitalReference.History[] getHospitalRecordByHospitalID(string hospital_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/getHospitalRecordByHospitalID", ReplyAction="http://tempuri.org/IHospitalService/getHospitalRecordByHospitalIDResponse")]
        System.Threading.Tasks.Task<Personal.Health.Record.HospitalReference.History[]> getHospitalRecordByHospitalIDAsync(string hospital_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/getHospitalRecordByDoctorID", ReplyAction="http://tempuri.org/IHospitalService/getHospitalRecordByDoctorIDResponse")]
        Personal.Health.Record.HospitalReference.History[] getHospitalRecordByDoctorID(string doctor_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/getHospitalRecordByDoctorID", ReplyAction="http://tempuri.org/IHospitalService/getHospitalRecordByDoctorIDResponse")]
        System.Threading.Tasks.Task<Personal.Health.Record.HospitalReference.History[]> getHospitalRecordByDoctorIDAsync(string doctor_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/getHospitalRecordByDate", ReplyAction="http://tempuri.org/IHospitalService/getHospitalRecordByDateResponse")]
        Personal.Health.Record.HospitalReference.History[] getHospitalRecordByDate(string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/getHospitalRecordByDate", ReplyAction="http://tempuri.org/IHospitalService/getHospitalRecordByDateResponse")]
        System.Threading.Tasks.Task<Personal.Health.Record.HospitalReference.History[]> getHospitalRecordByDateAsync(string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/addNewHospitalRecord", ReplyAction="http://tempuri.org/IHospitalService/addNewHospitalRecordResponse")]
        Personal.Health.Record.HospitalReference.History[] addNewHospitalRecord(string id, string patient_id, string hospital_id, string doctor_id, string reason, string diagnose, string date, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/addNewHospitalRecord", ReplyAction="http://tempuri.org/IHospitalService/addNewHospitalRecordResponse")]
        System.Threading.Tasks.Task<Personal.Health.Record.HospitalReference.History[]> addNewHospitalRecordAsync(string id, string patient_id, string hospital_id, string doctor_id, string reason, string diagnose, string date, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/GetVisitation", ReplyAction="http://tempuri.org/IHospitalService/GetVisitationResponse")]
        Personal.Health.Record.HospitalReference.ScheduledVisitation[] GetVisitation(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/GetVisitation", ReplyAction="http://tempuri.org/IHospitalService/GetVisitationResponse")]
        System.Threading.Tasks.Task<Personal.Health.Record.HospitalReference.ScheduledVisitation[]> GetVisitationAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/GetVisitationByPatientID", ReplyAction="http://tempuri.org/IHospitalService/GetVisitationByPatientIDResponse")]
        Personal.Health.Record.HospitalReference.ScheduledVisitation[] GetVisitationByPatientID(string patient_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/GetVisitationByPatientID", ReplyAction="http://tempuri.org/IHospitalService/GetVisitationByPatientIDResponse")]
        System.Threading.Tasks.Task<Personal.Health.Record.HospitalReference.ScheduledVisitation[]> GetVisitationByPatientIDAsync(string patient_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/GetVisitationByHospitalID", ReplyAction="http://tempuri.org/IHospitalService/GetVisitationByHospitalIDResponse")]
        Personal.Health.Record.HospitalReference.ScheduledVisitation[] GetVisitationByHospitalID(string hospital_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/GetVisitationByHospitalID", ReplyAction="http://tempuri.org/IHospitalService/GetVisitationByHospitalIDResponse")]
        System.Threading.Tasks.Task<Personal.Health.Record.HospitalReference.ScheduledVisitation[]> GetVisitationByHospitalIDAsync(string hospital_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/GetVisitationByDoctorID", ReplyAction="http://tempuri.org/IHospitalService/GetVisitationByDoctorIDResponse")]
        Personal.Health.Record.HospitalReference.ScheduledVisitation[] GetVisitationByDoctorID(string doctor_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/GetVisitationByDoctorID", ReplyAction="http://tempuri.org/IHospitalService/GetVisitationByDoctorIDResponse")]
        System.Threading.Tasks.Task<Personal.Health.Record.HospitalReference.ScheduledVisitation[]> GetVisitationByDoctorIDAsync(string doctor_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/GetVisitationByDate", ReplyAction="http://tempuri.org/IHospitalService/GetVisitationByDateResponse")]
        Personal.Health.Record.HospitalReference.ScheduledVisitation[] GetVisitationByDate(string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/GetVisitationByDate", ReplyAction="http://tempuri.org/IHospitalService/GetVisitationByDateResponse")]
        System.Threading.Tasks.Task<Personal.Health.Record.HospitalReference.ScheduledVisitation[]> GetVisitationByDateAsync(string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/AddNewVisitation", ReplyAction="http://tempuri.org/IHospitalService/AddNewVisitationResponse")]
        string AddNewVisitation(string id, string patient_id, string hospital_id, string doctor_id, string reason, string diagnose, string date, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitalService/AddNewVisitation", ReplyAction="http://tempuri.org/IHospitalService/AddNewVisitationResponse")]
        System.Threading.Tasks.Task<string> AddNewVisitationAsync(string id, string patient_id, string hospital_id, string doctor_id, string reason, string diagnose, string date, string description);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHospitalServiceChannel : Personal.Health.Record.HospitalReference.IHospitalService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HospitalServiceClient : System.ServiceModel.ClientBase<Personal.Health.Record.HospitalReference.IHospitalService>, Personal.Health.Record.HospitalReference.IHospitalService {
        
        public HospitalServiceClient() {
        }
        
        public HospitalServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HospitalServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HospitalServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HospitalServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Personal.Health.Record.HospitalReference.Patient[] getPatient(string id) {
            return base.Channel.getPatient(id);
        }
        
        public System.Threading.Tasks.Task<Personal.Health.Record.HospitalReference.Patient[]> getPatientAsync(string id) {
            return base.Channel.getPatientAsync(id);
        }
        
        public Personal.Health.Record.HospitalReference.Patient[] getUserByUsernameAndPassword(string username, string password) {
            return base.Channel.getUserByUsernameAndPassword(username, password);
        }
        
        public System.Threading.Tasks.Task<Personal.Health.Record.HospitalReference.Patient[]> getUserByUsernameAndPasswordAsync(string username, string password) {
            return base.Channel.getUserByUsernameAndPasswordAsync(username, password);
        }
        
        public Personal.Health.Record.HospitalReference.Patient[] getUserByEGNAndPassword(string egn, string password) {
            return base.Channel.getUserByEGNAndPassword(egn, password);
        }
        
        public System.Threading.Tasks.Task<Personal.Health.Record.HospitalReference.Patient[]> getUserByEGNAndPasswordAsync(string egn, string password) {
            return base.Channel.getUserByEGNAndPasswordAsync(egn, password);
        }
        
        public string AddNewPatient(string id, string gender, string username, string password, string first_name, string second_name, string last_name, string egn, string age, string birth_date) {
            return base.Channel.AddNewPatient(id, gender, username, password, first_name, second_name, last_name, egn, age, birth_date);
        }
        
        public System.Threading.Tasks.Task<string> AddNewPatientAsync(string id, string gender, string username, string password, string first_name, string second_name, string last_name, string egn, string age, string birth_date) {
            return base.Channel.AddNewPatientAsync(id, gender, username, password, first_name, second_name, last_name, egn, age, birth_date);
        }
        
        public Personal.Health.Record.HospitalReference.HospitalModel[] getHospital(string id) {
            return base.Channel.getHospital(id);
        }
        
        public System.Threading.Tasks.Task<Personal.Health.Record.HospitalReference.HospitalModel[]> getHospitalAsync(string id) {
            return base.Channel.getHospitalAsync(id);
        }
        
        public Personal.Health.Record.HospitalReference.Doctor[] getDoctor(string id) {
            return base.Channel.getDoctor(id);
        }
        
        public System.Threading.Tasks.Task<Personal.Health.Record.HospitalReference.Doctor[]> getDoctorAsync(string id) {
            return base.Channel.getDoctorAsync(id);
        }
        
        public Personal.Health.Record.HospitalReference.Doctor[] getDoctorByHospitalId(string hospital_id) {
            return base.Channel.getDoctorByHospitalId(hospital_id);
        }
        
        public System.Threading.Tasks.Task<Personal.Health.Record.HospitalReference.Doctor[]> getDoctorByHospitalIdAsync(string hospital_id) {
            return base.Channel.getDoctorByHospitalIdAsync(hospital_id);
        }
        
        public Personal.Health.Record.HospitalReference.Allergy[] getAllAllergies() {
            return base.Channel.getAllAllergies();
        }
        
        public System.Threading.Tasks.Task<Personal.Health.Record.HospitalReference.Allergy[]> getAllAllergiesAsync() {
            return base.Channel.getAllAllergiesAsync();
        }
        
        public string AddNewAllergy(string allergy_id) {
            return base.Channel.AddNewAllergy(allergy_id);
        }
        
        public System.Threading.Tasks.Task<string> AddNewAllergyAsync(string allergy_id) {
            return base.Channel.AddNewAllergyAsync(allergy_id);
        }
        
        public Personal.Health.Record.HospitalReference.History[] getHospitalRecord(string id) {
            return base.Channel.getHospitalRecord(id);
        }
        
        public System.Threading.Tasks.Task<Personal.Health.Record.HospitalReference.History[]> getHospitalRecordAsync(string id) {
            return base.Channel.getHospitalRecordAsync(id);
        }
        
        public Personal.Health.Record.HospitalReference.History[] getHospitalRecordByPatientID(string patient_id) {
            return base.Channel.getHospitalRecordByPatientID(patient_id);
        }
        
        public System.Threading.Tasks.Task<Personal.Health.Record.HospitalReference.History[]> getHospitalRecordByPatientIDAsync(string patient_id) {
            return base.Channel.getHospitalRecordByPatientIDAsync(patient_id);
        }
        
        public Personal.Health.Record.HospitalReference.History[] getHospitalRecordByHospitalID(string hospital_id) {
            return base.Channel.getHospitalRecordByHospitalID(hospital_id);
        }
        
        public System.Threading.Tasks.Task<Personal.Health.Record.HospitalReference.History[]> getHospitalRecordByHospitalIDAsync(string hospital_id) {
            return base.Channel.getHospitalRecordByHospitalIDAsync(hospital_id);
        }
        
        public Personal.Health.Record.HospitalReference.History[] getHospitalRecordByDoctorID(string doctor_id) {
            return base.Channel.getHospitalRecordByDoctorID(doctor_id);
        }
        
        public System.Threading.Tasks.Task<Personal.Health.Record.HospitalReference.History[]> getHospitalRecordByDoctorIDAsync(string doctor_id) {
            return base.Channel.getHospitalRecordByDoctorIDAsync(doctor_id);
        }
        
        public Personal.Health.Record.HospitalReference.History[] getHospitalRecordByDate(string date) {
            return base.Channel.getHospitalRecordByDate(date);
        }
        
        public System.Threading.Tasks.Task<Personal.Health.Record.HospitalReference.History[]> getHospitalRecordByDateAsync(string date) {
            return base.Channel.getHospitalRecordByDateAsync(date);
        }
        
        public Personal.Health.Record.HospitalReference.History[] addNewHospitalRecord(string id, string patient_id, string hospital_id, string doctor_id, string reason, string diagnose, string date, string description) {
            return base.Channel.addNewHospitalRecord(id, patient_id, hospital_id, doctor_id, reason, diagnose, date, description);
        }
        
        public System.Threading.Tasks.Task<Personal.Health.Record.HospitalReference.History[]> addNewHospitalRecordAsync(string id, string patient_id, string hospital_id, string doctor_id, string reason, string diagnose, string date, string description) {
            return base.Channel.addNewHospitalRecordAsync(id, patient_id, hospital_id, doctor_id, reason, diagnose, date, description);
        }
        
        public Personal.Health.Record.HospitalReference.ScheduledVisitation[] GetVisitation(string id) {
            return base.Channel.GetVisitation(id);
        }
        
        public System.Threading.Tasks.Task<Personal.Health.Record.HospitalReference.ScheduledVisitation[]> GetVisitationAsync(string id) {
            return base.Channel.GetVisitationAsync(id);
        }
        
        public Personal.Health.Record.HospitalReference.ScheduledVisitation[] GetVisitationByPatientID(string patient_id) {
            return base.Channel.GetVisitationByPatientID(patient_id);
        }
        
        public System.Threading.Tasks.Task<Personal.Health.Record.HospitalReference.ScheduledVisitation[]> GetVisitationByPatientIDAsync(string patient_id) {
            return base.Channel.GetVisitationByPatientIDAsync(patient_id);
        }
        
        public Personal.Health.Record.HospitalReference.ScheduledVisitation[] GetVisitationByHospitalID(string hospital_id) {
            return base.Channel.GetVisitationByHospitalID(hospital_id);
        }
        
        public System.Threading.Tasks.Task<Personal.Health.Record.HospitalReference.ScheduledVisitation[]> GetVisitationByHospitalIDAsync(string hospital_id) {
            return base.Channel.GetVisitationByHospitalIDAsync(hospital_id);
        }
        
        public Personal.Health.Record.HospitalReference.ScheduledVisitation[] GetVisitationByDoctorID(string doctor_id) {
            return base.Channel.GetVisitationByDoctorID(doctor_id);
        }
        
        public System.Threading.Tasks.Task<Personal.Health.Record.HospitalReference.ScheduledVisitation[]> GetVisitationByDoctorIDAsync(string doctor_id) {
            return base.Channel.GetVisitationByDoctorIDAsync(doctor_id);
        }
        
        public Personal.Health.Record.HospitalReference.ScheduledVisitation[] GetVisitationByDate(string date) {
            return base.Channel.GetVisitationByDate(date);
        }
        
        public System.Threading.Tasks.Task<Personal.Health.Record.HospitalReference.ScheduledVisitation[]> GetVisitationByDateAsync(string date) {
            return base.Channel.GetVisitationByDateAsync(date);
        }
        
        public string AddNewVisitation(string id, string patient_id, string hospital_id, string doctor_id, string reason, string diagnose, string date, string description) {
            return base.Channel.AddNewVisitation(id, patient_id, hospital_id, doctor_id, reason, diagnose, date, description);
        }
        
        public System.Threading.Tasks.Task<string> AddNewVisitationAsync(string id, string patient_id, string hospital_id, string doctor_id, string reason, string diagnose, string date, string description) {
            return base.Channel.AddNewVisitationAsync(id, patient_id, hospital_id, doctor_id, reason, diagnose, date, description);
        }
    }
}
