//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personal.Health.Services.Impl.HospitalServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HospitalServiceReference.HospitalWebService")]
    public interface HospitalWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HospitalWebService/GetPatient", ReplyAction="http://tempuri.org/HospitalWebService/GetPatientResponse")]
        string GetPatient(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HospitalWebService/GetPatient", ReplyAction="http://tempuri.org/HospitalWebService/GetPatientResponse")]
        System.Threading.Tasks.Task<string> GetPatientAsync(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HospitalWebService/GetPatientByUsernameAndPassword", ReplyAction="http://tempuri.org/HospitalWebService/GetPatientByUsernameAndPasswordResponse")]
        string GetPatientByUsernameAndPassword(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HospitalWebService/GetPatientByUsernameAndPassword", ReplyAction="http://tempuri.org/HospitalWebService/GetPatientByUsernameAndPasswordResponse")]
        System.Threading.Tasks.Task<string> GetPatientByUsernameAndPasswordAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HospitalWebService/GetPatientByEGNAndPassword", ReplyAction="http://tempuri.org/HospitalWebService/GetPatientByEGNAndPasswordResponse")]
        string GetPatientByEGNAndPassword(string egn, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HospitalWebService/GetPatientByEGNAndPassword", ReplyAction="http://tempuri.org/HospitalWebService/GetPatientByEGNAndPasswordResponse")]
        System.Threading.Tasks.Task<string> GetPatientByEGNAndPasswordAsync(string egn, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HospitalWebService/AddNewPatient", ReplyAction="http://tempuri.org/HospitalWebService/AddNewPatientResponse")]
        bool AddNewPatient(long id, string gender, string username, string password, string first_name, string second_name, string last_name, string egn, int age, string birth_date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HospitalWebService/AddNewPatient", ReplyAction="http://tempuri.org/HospitalWebService/AddNewPatientResponse")]
        System.Threading.Tasks.Task<bool> AddNewPatientAsync(long id, string gender, string username, string password, string first_name, string second_name, string last_name, string egn, int age, string birth_date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HospitalWebService/GetHospital", ReplyAction="http://tempuri.org/HospitalWebService/GetHospitalResponse")]
        string GetHospital(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HospitalWebService/GetHospital", ReplyAction="http://tempuri.org/HospitalWebService/GetHospitalResponse")]
        System.Threading.Tasks.Task<string> GetHospitalAsync(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HospitalWebService/GetAllHospitals", ReplyAction="http://tempuri.org/HospitalWebService/GetAllHospitalsResponse")]
        string GetAllHospitals();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HospitalWebService/GetAllHospitals", ReplyAction="http://tempuri.org/HospitalWebService/GetAllHospitalsResponse")]
        System.Threading.Tasks.Task<string> GetAllHospitalsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HospitalWebService/GetDoctor", ReplyAction="http://tempuri.org/HospitalWebService/GetDoctorResponse")]
        string GetDoctor(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HospitalWebService/GetDoctor", ReplyAction="http://tempuri.org/HospitalWebService/GetDoctorResponse")]
        System.Threading.Tasks.Task<string> GetDoctorAsync(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HospitalWebService/GetDoctorsByHospitalId", ReplyAction="http://tempuri.org/HospitalWebService/GetDoctorsByHospitalIdResponse")]
        string GetDoctorsByHospitalId(long hospital_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HospitalWebService/GetDoctorsByHospitalId", ReplyAction="http://tempuri.org/HospitalWebService/GetDoctorsByHospitalIdResponse")]
        System.Threading.Tasks.Task<string> GetDoctorsByHospitalIdAsync(long hospital_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HospitalWebService/GetAllDoctors", ReplyAction="http://tempuri.org/HospitalWebService/GetAllDoctorsResponse")]
        string GetAllDoctors();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HospitalWebService/GetAllDoctors", ReplyAction="http://tempuri.org/HospitalWebService/GetAllDoctorsResponse")]
        System.Threading.Tasks.Task<string> GetAllDoctorsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HospitalWebService/GetAllAllergies", ReplyAction="http://tempuri.org/HospitalWebService/GetAllAllergiesResponse")]
        string GetAllAllergies();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HospitalWebService/GetAllAllergies", ReplyAction="http://tempuri.org/HospitalWebService/GetAllAllergiesResponse")]
        System.Threading.Tasks.Task<string> GetAllAllergiesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HospitalWebService/GetHospitalRecord", ReplyAction="http://tempuri.org/HospitalWebService/GetHospitalRecordResponse")]
        string GetHospitalRecord(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HospitalWebService/GetHospitalRecord", ReplyAction="http://tempuri.org/HospitalWebService/GetHospitalRecordResponse")]
        System.Threading.Tasks.Task<string> GetHospitalRecordAsync(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HospitalWebService/GetHospitalRecordByPatientID", ReplyAction="http://tempuri.org/HospitalWebService/GetHospitalRecordByPatientIDResponse")]
        string GetHospitalRecordByPatientID(long patient_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HospitalWebService/GetHospitalRecordByPatientID", ReplyAction="http://tempuri.org/HospitalWebService/GetHospitalRecordByPatientIDResponse")]
        System.Threading.Tasks.Task<string> GetHospitalRecordByPatientIDAsync(long patient_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HospitalWebService/GetHospitalRecordByHospitalID", ReplyAction="http://tempuri.org/HospitalWebService/GetHospitalRecordByHospitalIDResponse")]
        string GetHospitalRecordByHospitalID(long hospital_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HospitalWebService/GetHospitalRecordByHospitalID", ReplyAction="http://tempuri.org/HospitalWebService/GetHospitalRecordByHospitalIDResponse")]
        System.Threading.Tasks.Task<string> GetHospitalRecordByHospitalIDAsync(long hospital_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HospitalWebService/GetHospitalRecordByDoctorID", ReplyAction="http://tempuri.org/HospitalWebService/GetHospitalRecordByDoctorIDResponse")]
        string GetHospitalRecordByDoctorID(long doctor_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HospitalWebService/GetHospitalRecordByDoctorID", ReplyAction="http://tempuri.org/HospitalWebService/GetHospitalRecordByDoctorIDResponse")]
        System.Threading.Tasks.Task<string> GetHospitalRecordByDoctorIDAsync(long doctor_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HospitalWebService/GetHospitalRecordByDate", ReplyAction="http://tempuri.org/HospitalWebService/GetHospitalRecordByDateResponse")]
        string GetHospitalRecordByDate(string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HospitalWebService/GetHospitalRecordByDate", ReplyAction="http://tempuri.org/HospitalWebService/GetHospitalRecordByDateResponse")]
        System.Threading.Tasks.Task<string> GetHospitalRecordByDateAsync(string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HospitalWebService/AddNewHospitalRecord", ReplyAction="http://tempuri.org/HospitalWebService/AddNewHospitalRecordResponse")]
        string AddNewHospitalRecord(long id, long patient_id, long hospital_id, long doctor_id, string reason, string diagnose, string date, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HospitalWebService/AddNewHospitalRecord", ReplyAction="http://tempuri.org/HospitalWebService/AddNewHospitalRecordResponse")]
        System.Threading.Tasks.Task<string> AddNewHospitalRecordAsync(long id, long patient_id, long hospital_id, long doctor_id, string reason, string diagnose, string date, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HospitalWebService/GetVisitation", ReplyAction="http://tempuri.org/HospitalWebService/GetVisitationResponse")]
        string GetVisitation(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HospitalWebService/GetVisitation", ReplyAction="http://tempuri.org/HospitalWebService/GetVisitationResponse")]
        System.Threading.Tasks.Task<string> GetVisitationAsync(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HospitalWebService/GetVisitationByPatientID", ReplyAction="http://tempuri.org/HospitalWebService/GetVisitationByPatientIDResponse")]
        string GetVisitationByPatientID(long patient_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HospitalWebService/GetVisitationByPatientID", ReplyAction="http://tempuri.org/HospitalWebService/GetVisitationByPatientIDResponse")]
        System.Threading.Tasks.Task<string> GetVisitationByPatientIDAsync(long patient_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HospitalWebService/GetVisitationByHospitalID", ReplyAction="http://tempuri.org/HospitalWebService/GetVisitationByHospitalIDResponse")]
        string GetVisitationByHospitalID(long hospital_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HospitalWebService/GetVisitationByHospitalID", ReplyAction="http://tempuri.org/HospitalWebService/GetVisitationByHospitalIDResponse")]
        System.Threading.Tasks.Task<string> GetVisitationByHospitalIDAsync(long hospital_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HospitalWebService/GetVisitationByDoctorID", ReplyAction="http://tempuri.org/HospitalWebService/GetVisitationByDoctorIDResponse")]
        string GetVisitationByDoctorID(long doctor_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HospitalWebService/GetVisitationByDoctorID", ReplyAction="http://tempuri.org/HospitalWebService/GetVisitationByDoctorIDResponse")]
        System.Threading.Tasks.Task<string> GetVisitationByDoctorIDAsync(long doctor_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HospitalWebService/GetVisitationByDate", ReplyAction="http://tempuri.org/HospitalWebService/GetVisitationByDateResponse")]
        string GetVisitationByDate(string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HospitalWebService/GetVisitationByDate", ReplyAction="http://tempuri.org/HospitalWebService/GetVisitationByDateResponse")]
        System.Threading.Tasks.Task<string> GetVisitationByDateAsync(string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HospitalWebService/AddNewVisitation", ReplyAction="http://tempuri.org/HospitalWebService/AddNewVisitationResponse")]
        string AddNewVisitation(long id, long patient_id, long hospital_id, long doctor_id, string reason, string diagnose, string date, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HospitalWebService/AddNewVisitation", ReplyAction="http://tempuri.org/HospitalWebService/AddNewVisitationResponse")]
        System.Threading.Tasks.Task<string> AddNewVisitationAsync(long id, long patient_id, long hospital_id, long doctor_id, string reason, string diagnose, string date, string description);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HospitalWebServiceChannel : Personal.Health.Services.Impl.HospitalServiceReference.HospitalWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HospitalWebServiceClient : System.ServiceModel.ClientBase<Personal.Health.Services.Impl.HospitalServiceReference.HospitalWebService>, Personal.Health.Services.Impl.HospitalServiceReference.HospitalWebService {
        
        public HospitalWebServiceClient() {
        }
        
        public HospitalWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HospitalWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HospitalWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HospitalWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetPatient(long id) {
            return base.Channel.GetPatient(id);
        }
        
        public System.Threading.Tasks.Task<string> GetPatientAsync(long id) {
            return base.Channel.GetPatientAsync(id);
        }
        
        public string GetPatientByUsernameAndPassword(string username, string password) {
            return base.Channel.GetPatientByUsernameAndPassword(username, password);
        }
        
        public System.Threading.Tasks.Task<string> GetPatientByUsernameAndPasswordAsync(string username, string password) {
            return base.Channel.GetPatientByUsernameAndPasswordAsync(username, password);
        }
        
        public string GetPatientByEGNAndPassword(string egn, string password) {
            return base.Channel.GetPatientByEGNAndPassword(egn, password);
        }
        
        public System.Threading.Tasks.Task<string> GetPatientByEGNAndPasswordAsync(string egn, string password) {
            return base.Channel.GetPatientByEGNAndPasswordAsync(egn, password);
        }
        
        public bool AddNewPatient(long id, string gender, string username, string password, string first_name, string second_name, string last_name, string egn, int age, string birth_date) {
            return base.Channel.AddNewPatient(id, gender, username, password, first_name, second_name, last_name, egn, age, birth_date);
        }
        
        public System.Threading.Tasks.Task<bool> AddNewPatientAsync(long id, string gender, string username, string password, string first_name, string second_name, string last_name, string egn, int age, string birth_date) {
            return base.Channel.AddNewPatientAsync(id, gender, username, password, first_name, second_name, last_name, egn, age, birth_date);
        }
        
        public string GetHospital(long id) {
            return base.Channel.GetHospital(id);
        }
        
        public System.Threading.Tasks.Task<string> GetHospitalAsync(long id) {
            return base.Channel.GetHospitalAsync(id);
        }
        
        public string GetAllHospitals() {
            return base.Channel.GetAllHospitals();
        }
        
        public System.Threading.Tasks.Task<string> GetAllHospitalsAsync() {
            return base.Channel.GetAllHospitalsAsync();
        }
        
        public string GetDoctor(long id) {
            return base.Channel.GetDoctor(id);
        }
        
        public System.Threading.Tasks.Task<string> GetDoctorAsync(long id) {
            return base.Channel.GetDoctorAsync(id);
        }
        
        public string GetDoctorsByHospitalId(long hospital_id) {
            return base.Channel.GetDoctorsByHospitalId(hospital_id);
        }
        
        public System.Threading.Tasks.Task<string> GetDoctorsByHospitalIdAsync(long hospital_id) {
            return base.Channel.GetDoctorsByHospitalIdAsync(hospital_id);
        }
        
        public string GetAllDoctors() {
            return base.Channel.GetAllDoctors();
        }
        
        public System.Threading.Tasks.Task<string> GetAllDoctorsAsync() {
            return base.Channel.GetAllDoctorsAsync();
        }
        
        public string GetAllAllergies() {
            return base.Channel.GetAllAllergies();
        }
        
        public System.Threading.Tasks.Task<string> GetAllAllergiesAsync() {
            return base.Channel.GetAllAllergiesAsync();
        }
        
        public string GetHospitalRecord(long id) {
            return base.Channel.GetHospitalRecord(id);
        }
        
        public System.Threading.Tasks.Task<string> GetHospitalRecordAsync(long id) {
            return base.Channel.GetHospitalRecordAsync(id);
        }
        
        public string GetHospitalRecordByPatientID(long patient_id) {
            return base.Channel.GetHospitalRecordByPatientID(patient_id);
        }
        
        public System.Threading.Tasks.Task<string> GetHospitalRecordByPatientIDAsync(long patient_id) {
            return base.Channel.GetHospitalRecordByPatientIDAsync(patient_id);
        }
        
        public string GetHospitalRecordByHospitalID(long hospital_id) {
            return base.Channel.GetHospitalRecordByHospitalID(hospital_id);
        }
        
        public System.Threading.Tasks.Task<string> GetHospitalRecordByHospitalIDAsync(long hospital_id) {
            return base.Channel.GetHospitalRecordByHospitalIDAsync(hospital_id);
        }
        
        public string GetHospitalRecordByDoctorID(long doctor_id) {
            return base.Channel.GetHospitalRecordByDoctorID(doctor_id);
        }
        
        public System.Threading.Tasks.Task<string> GetHospitalRecordByDoctorIDAsync(long doctor_id) {
            return base.Channel.GetHospitalRecordByDoctorIDAsync(doctor_id);
        }
        
        public string GetHospitalRecordByDate(string date) {
            return base.Channel.GetHospitalRecordByDate(date);
        }
        
        public System.Threading.Tasks.Task<string> GetHospitalRecordByDateAsync(string date) {
            return base.Channel.GetHospitalRecordByDateAsync(date);
        }
        
        public string AddNewHospitalRecord(long id, long patient_id, long hospital_id, long doctor_id, string reason, string diagnose, string date, string description) {
            return base.Channel.AddNewHospitalRecord(id, patient_id, hospital_id, doctor_id, reason, diagnose, date, description);
        }
        
        public System.Threading.Tasks.Task<string> AddNewHospitalRecordAsync(long id, long patient_id, long hospital_id, long doctor_id, string reason, string diagnose, string date, string description) {
            return base.Channel.AddNewHospitalRecordAsync(id, patient_id, hospital_id, doctor_id, reason, diagnose, date, description);
        }
        
        public string GetVisitation(long id) {
            return base.Channel.GetVisitation(id);
        }
        
        public System.Threading.Tasks.Task<string> GetVisitationAsync(long id) {
            return base.Channel.GetVisitationAsync(id);
        }
        
        public string GetVisitationByPatientID(long patient_id) {
            return base.Channel.GetVisitationByPatientID(patient_id);
        }
        
        public System.Threading.Tasks.Task<string> GetVisitationByPatientIDAsync(long patient_id) {
            return base.Channel.GetVisitationByPatientIDAsync(patient_id);
        }
        
        public string GetVisitationByHospitalID(long hospital_id) {
            return base.Channel.GetVisitationByHospitalID(hospital_id);
        }
        
        public System.Threading.Tasks.Task<string> GetVisitationByHospitalIDAsync(long hospital_id) {
            return base.Channel.GetVisitationByHospitalIDAsync(hospital_id);
        }
        
        public string GetVisitationByDoctorID(long doctor_id) {
            return base.Channel.GetVisitationByDoctorID(doctor_id);
        }
        
        public System.Threading.Tasks.Task<string> GetVisitationByDoctorIDAsync(long doctor_id) {
            return base.Channel.GetVisitationByDoctorIDAsync(doctor_id);
        }
        
        public string GetVisitationByDate(string date) {
            return base.Channel.GetVisitationByDate(date);
        }
        
        public System.Threading.Tasks.Task<string> GetVisitationByDateAsync(string date) {
            return base.Channel.GetVisitationByDateAsync(date);
        }
        
        public string AddNewVisitation(long id, long patient_id, long hospital_id, long doctor_id, string reason, string diagnose, string date, string description) {
            return base.Channel.AddNewVisitation(id, patient_id, hospital_id, doctor_id, reason, diagnose, date, description);
        }
        
        public System.Threading.Tasks.Task<string> AddNewVisitationAsync(long id, long patient_id, long hospital_id, long doctor_id, string reason, string diagnose, string date, string description) {
            return base.Channel.AddNewVisitationAsync(id, patient_id, hospital_id, doctor_id, reason, diagnose, date, description);
        }
    }
}
